language: php

dist: trusty

sudo: false

env:
    global:
        - APP_ENV=test_cached
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

addons:
    apt:
        sources:
            - mysql-5.7-trusty

matrix:
    include:
        -
            php: 7.3
            env:
                - SYLIUS_SUITE="application"
                - SYMFONY_VERSION="4.4.*"
            services:
                - memcached
                - mysql
#        -
#            php: 7.3
#            env:
#                - SYLIUS_SUITE="docs packages"
#                - SYMFONY_VERSION="4.4.*"
#            services:
#                - docker
#            addons:
#                apt:
#                    packages:
#                        - parallel

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - ~/.cache/pip
        - node_modules
        - $SYLIUS_CACHE_DIR

before_install:
    - etc/travis/run-suite before_install "${SYLIUS_SUITE}"

install:
    - etc/travis/run-suite install "${SYLIUS_SUITE}"

before_script:
    - etc/travis/run-suite before_script "${SYLIUS_SUITE}"

script:
#    - etc/travis/run-suite script "${SYLIUS_SUITE}"
    - gem install travis
    - travis encrypt "sylius:5QI8kVi8f8kAB04st9ngD40H" --add notifications.slack.rooms

before_cache:
    - etc/travis/run-suite before_cache "${SYLIUS_SUITE}"

after_success:
    - etc/travis/run-suite after_success "${SYLIUS_SUITE}"

after_failure:
    - etc/travis/run-suite after_failure "${SYLIUS_SUITE}"

after_script:
    - etc/travis/run-suite after_script "${SYLIUS_SUITE}"

notifications:
    email: false
    slack:
        on_success: always
        on_error: always
        template:
            - "Cron build on `%{branch}` branch of *%{repository_slug}* has failed :sadbono:"
            - "Check out <%{build_url}|this URL> and fix it!"
